---
kind: pipeline
name: matrix-1
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: plugins/docker
  settings:
    build_args:
    - TERRAFORM_VERSION=0.12.25
    - TERRAGRUNT_VERSION=0.23.18
    context: app
    dockerfile: app/Dockerfile
    force_tag: true
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dq-docker-terragrunt
    tags:
    - ${DRONE_COMMIT_SHA}
    - ${DRONE_BUILD_NUMBER}
    - v0.23.18
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - push

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
